# -------------------------------------------------------------------
# Configuración Oficial de SonarQube
# -------------------------------------------------------------------

# Identificador único del proyecto (Debes reemplazarlo con el tuyo real al crear el proyecto en SonarCloud)
sonar.projectKey=yohanvillarp_quizsync
sonar.organization=yohanvillarp-1

# Metadatos
sonar.projectName=QuizSync
sonar.projectVersion=1.0

# Directorios a analizar (Escaneamos el código fuente de los 4 microservicios)
sonar.sources=apps/api-core/src, apps/game-engine/src, apps/cliente/src, apps/studio/src

# Exclusiones (No queremos escanear dependencias, builds ni código de pruebas)
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, apps/qa/**, **/*.spec.ts, **/*.test.ts

# Lenguajes principales del proyecto
sonar.language=ts

# Reportes de Cobertura de Pruebas (Coverage)
# ubicación de reportes generados por Jest en el backend
sonar.javascript.lcov.reportPaths=apps/api-core/coverage/lcov.info, apps/game-engine/coverage/lcov.info
